### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by fgeek** [k3170makan/GooDork#1]
Did you test your code at all? This is from your examples:

fgeek@kludge:~/scm/GooDork$ python GooDork.py site:.gov -bMissile
Searching >>site:.gov<<

200
OKContent-Type: text/html; charset=ISO-8859-1
Date: Mon, 02 Apr 2012 11:48:24 GMT
Expires: -1
Cache-Control: private, max-age=0
Set-Cookie: PREF=ID=efa8410ddb6f0998:FF=0:TM=1333367304:LM=1333367304:S=TkSWw9kHWwzULIcL; expires=Wed, 02-Apr-2014 11:48:24 GMT; path=/; domain=.google.com
Set-Cookie: NID=58=NE7SdpZlyBUW0Iq-oexFslhJaKfCnoIz4Po9RNdnHWWBWNhS9KhNWNnioNxuw3J7cbSavyUrtWGLjZSbTeBE0f4ZDgW4-aPbUiUCIhEb5IpyVyVJo63nG-bVkfT2-hWX; expires=Tue, 02-Oct-2012 11:48:24 GMT; path=/; domain=.google.com; HttpOnly
P3P: CP="This is not a P3P policy! See http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

Traceback (most recent call last):
  File "GooDork.py", line 78, in <module>
    dork.run()
  File "GooDork.py", line 16, in run
    links = self.operator.goosearch(sys.argv[1])
  File "/home/fgeek/scm/GooDork/Operator.py", line 41, in goosearch
    links = self.stripper.strip(page[1])
  File "/home/fgeek/scm/GooDork/URLStripper.py", line 13, in strip
    if len(results_wrapper) < 1:
TypeError: object of type 'NoneType' has no len()

**Comment by k3170makan** [comment]
No problem, I'll fix this up on Wednesday, most other dorks should work fine. Please let me know if you find one that doesn't ;)

**Comment by fgeek** [comment]
How should it work?

fgeek@kludge:~/scm/GooDork$ python GooDork.py  foobar
Searching >>foobar<<

200
OKContent-Type: text/html; charset=ISO-8859-1
Date: Mon, 02 Apr 2012 13:18:32 GMT
Expires: -1
Cache-Control: private, max-age=0
Set-Cookie: PREF=ID=cb823c8c2f0c76e0:FF=0:TM=1333372712:LM=1333372712:S=ZzSBeAXvU5ggHNmP; expires=Wed, 02-Apr-2014 13:18:32 GMT; path=/; domain=.google.com
Set-Cookie: NID=58=R5XJ1v8-wwoTJVi6r_weACi-eKTjp19PLTnUGQuORkNt-dNi4WWHzFThIYI1CNjcIqyFyDplATpsVEui0WB_J-O0L1bf4yx3dOgittFi9c7qT6__uiLDCGgHe5JZxuCb; expires=Tue, 02-Oct-2012 13:18:32 GMT; path=/; domain=.google.com; HttpOnly
P3P: CP="This is not a P3P policy! See http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

Traceback (most recent call last):
  File "GooDork.py", line 78, in <module>
    dork.run()
  File "GooDork.py", line 16, in run
    links = self.operator.goosearch(sys.argv[1])
  File "/home/fgeek/scm/GooDork/Operator.py", line 41, in goosearch
    links = self.stripper.strip(page[1])
  File "/home/fgeek/scm/GooDork/URLStripper.py", line 13, in strip
    if len(results_wrapper) < 1:
TypeError: object of type 'NoneType' has no len()

**Comment by k3170makan** [comment]
Are you working behind a proxy perhaps?

On 4/2/12, Henri Salo
reply@reply.github.com
wrote:

**Comment by k3170makan** [comment]
Nah It's not that, I'll check this out when I get home, sorry about
this, I tested the code before I committed

**Comment by k3170makan** [comment]
I just checked it now, and YES i checked all the dorks except "foo" lols but this is what i get

 keith@keith  18:37:07  [0] ~

> ./GooDork/GooDork.py site:.gov
> Searching >>site:.gov<<

200
OKContent-Type: text/html; charset=ISO-8859-1
Date: Mon, 02 Apr 2012 16:37:16 GMT
Expires: -1
Cache-Control: private, max-age=0
Set-Cookie: PREF=ID=faf5219e7e922ee4:FF=0:TM=1333384636:LM=1333384636:S=wEWXUfxigHub2SiU; expires=Wed, 02-Apr-2014 16:37:16 GMT; path=/; domain=.google.com
Set-Cookie: NID=58=KEBksgvrZ7RpUVVp8-i17qF_byt2iE8E66mLkkAs7jR6HMxez4RycAx8fEg5UwC_z3ofQ8cd3VuaYuZgrzqVnV2Pb3hrEWzTzAkg0TwJta0tU3m0_mdhl6deCoCJh2Cv; expires=Tue, 02-Oct-2012 16:37:16 GMT; path=/; domain=.google.com; HttpOnly
P3P: CP="This is not a P3P policy! See http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

Results:
1:http://www.minnesota.gov/
2:http://www.roanokecountyva.gov/
3:http://www.recreation.gov/
4:http://www.albanyny.gov/
5:http://www.kentwa.gov/
6:http://www.capitalregionupdates.gov/
7:http://www.txdot.gov/
8:http://www.minneapolismn.gov/
9:http://nv.gov/
10:http://fedidcard.gov/
11:http://www.clarkcountynv.gov/
12:http://www.azdor.gov/
13:http://www.flsenate.gov/
14:http://www.norfolk.gov/
15:http://www.newmexico.gov/
16:http://www.mesaaz.gov/
17:http://www.detroitmi.gov/
18:http://www.phila.gov/
19:http://www.ohiosenate.gov/
20:http://www.sussexcountyde.gov/
21:http://www.wilmingtonnc.gov/
22:http://www.utcourts.gov/
23:http://www.cms.gov/
24:http://www.sanantonio.gov/
25:http://www.uscis.gov/
26:http://www.oregonmetro.gov/
27:http://www.azdot.gov/
28:http://www.sba.gov/
29:http://www.mo.gov/
30:http://www.alabama.gov/
31:http://www.houstontx.gov/
32:http://www.fairfaxcounty.gov/
33:http://www.ncdot.gov/
34:http://www.baycountyfl.gov/
35:http://www.hrsa.gov/
36:http://www.louisvilleky.gov/
37:http://www.bryantx.gov/
38:http://www.va.gov/
39:http://www.aldoi.gov/
40:http://www.huntingtonbeachca.gov/
41:http://www.bart.gov/
42:http://www.lowellma.gov/
43:http://www.vermont.gov/
44:http://www.ohioattorneygeneral.gov/
45:http://www.azgfd.gov/
46:http://www.michigan.gov/
47:http://www.sandiego.gov/
48:http://www.gaithersburgmd.gov/
49:http://www.ffiec.gov/
50:http://www.medicare.gov/
51:http://alexandriava.gov/
52:http://www.energycodes.gov/
53:http://www.cfoc.gov/
54:http://www.nationalservice.gov/
55:http://www.kauai.gov/
56:http://www.nd.gov/
57:http://www.azdps.gov/
58:http://www.secretservice.gov/
59:http://www.kansas.gov/
60:http://www.monroecounty.gov/
61:http://www.ttb.gov/
62:http://www.nrc.gov/
63:http://www.cancer.gov/
64:http://www.cio.gov/
65:http://www.az.gov/
66:http://www.fws.gov/
67:http://www.rockvillemd.gov/
68:http://www.in.gov/
69:http://www.cambridgema.gov/
70:http://www.lasvegasnevada.gov/
71:http://www.ferc.gov/
72:http://www.maine.gov/
73:http://www.scdhec.gov/
74:http://www.dnr.illinois.gov/
75:http://www.attorneygeneral.gov/
76:http://www.hhs.gov/
77:http://www.nps.gov/
78:http://www.santabarbaraca.gov/
79:http://www.virginia.gov/
80:http://www.azdhs.gov/
81:http://www.mbda.gov/
82:http://mcnerney.house.gov/
83:http://www.danville.ca.gov/
84:http://www.class.noaa.gov/
85:http://dpi.wi.gov/
86:http://legis.wisconsin.gov/
87:http://www.ct.gov/csc/
88:http://afghanistan.usaid.gov/
89:http://www.kirk.senate.gov/
90:http://www.tn.gov/twra/
91:http://www.oregon.gov/DHS/
92:http://exploration.nasa.gov/
93:http://www.usbr.gov/mp/
94:http://www.parks.ny.gov/
95:http://www.nj.gov/lps/
96:http://www.brunswickcountync.gov/
97:http://www.peoriaaz.gov/
98:http://www.ldaf.louisiana.gov/
99:http://www.anl.gov/

I think you need to install BeautifulSoup4
Are you running linux?

**Comment by fgeek** [comment]
Sorry for a bad bug-report. I previously did not have time to properly test this, but now I did I found out that the problem only occurs with Python 2.7, but not with 2.7.2.

**Comment by k3170makan** [comment]
No no its appreciated dude. Please let me know if you need anything else! I just dropped new commit here https://github.com/k3170makan/GooDork
